[package]
name = "sexp_native"
version = "0.1.0"
edition = "2021"

[lib]
name = "sexp_native"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
pyo3 = { version = "0.25", features = ["extension-module"] }
base64 = "0.22"
hex = "0.4"
